"""
Auto-generated orchestration script for path_2.
DO NOT EDIT - Generated by OrchestratorAgent Coder
Run ID: 20251124_173218
"""

import asyncio
import json
import logging
import time
from pathlib import Path
from typing import Dict, Any, Optional

from src.agents.polymarket_agent.run import PolymarketAgent

from src.agents.orchestrator_agent.workers_db import WorkersDB

logger = logging.getLogger(__name__)

# Configuration
RUN_ID = "20251124_173218"
DB_PATH = Path("Z:\Aastha\market_data_puller\workspace\orchestrator_results.db")


async def task_task_2() -> Dict[str, Any]:
    """
    Task task_2: Retrieve historical price series for Bitcoin from Polymarket
    Agent: polymarket_agent
    """
    task_id = "task_2"
    agent_name = "polymarket_agent"
    
    logger.info(f"Starting task {task_id}: Retrieve historical price series for Bitcoin from ...")
    
    # Record task start in DB
    with WorkersDB(DB_PATH) as db:
        db.start_task(RUN_ID, task_id, agent_name)
    
    start_time = time.time()
    
    try:
        # Execute agent
        agent = PolymarketAgent()
        output_path = agent.run(query="retrieve historical price series for bitcoin from polymarket", session_id=None, limit=10)
        
        duration_ms = (time.time() - start_time) * 1000
        
        logger.info(f"Task {task_id} completed: {output_path}")
        
        # Read output from file bus
        with open(output_path, 'r') as f:
            output_data = json.load(f)
        
        # Store in DB
        with WorkersDB(DB_PATH) as db:
            db.complete_task(
                RUN_ID,
                task_id,
                status='success',
                duration_ms=duration_ms,
                output_file_path=str(output_path)
            )
            db.store_task_output(
                RUN_ID,
                task_id,
                agent_name,
                output_data.get('data', []),
                output_data.get('metadata', {})
            )
        
        return {
            'status': 'success',
            'task_id': task_id,
            'agent': agent_name,
            'output_path': str(output_path),
            'data': output_data,
            'duration_ms': duration_ms,
            'error': None
        }
        
    except Exception as e:
        duration_ms = (time.time() - start_time) * 1000
        
        logger.error(f"Task {task_id} failed: {e}")
        
        # Record failure in DB
        with WorkersDB(DB_PATH) as db:
            db.complete_task(
                RUN_ID,
                task_id,
                status='failed',
                duration_ms=duration_ms,
                error=str(e)
            )
        
        return {
            'status': 'failed',
            'task_id': task_id,
            'agent': agent_name,
            'output_path': None,
            'data': None,
            'duration_ms': duration_ms,
            'error': str(e)
        }



async def main() -> list:
    """Main orchestration function - parallel execution."""
    logger.info("Starting parallel execution of 1 tasks")
    
    results = await asyncio.gather(
        task_task_2()
    )
    
    logger.info("All tasks completed")
    return list(results)



if __name__ == "__main__":
    # Run the orchestration
    results = asyncio.run(main())
    
    # Print summary
    print("\n" + "="*60)
    print(f"PATH: path_2")
    print("="*60)
    for i, result in enumerate(results, 1):
        status = "✓ SUCCESS" if result.get('status') == 'success' else "✗ FAILED"
        task_id = result.get('task_id', 'unknown')
        print(f"Task {task_id}: {status}")
        if result.get('error'):
            print(f"  Error: {result['error']}")
    print("="*60)
