"""
Auto-generated orchestration script.
DO NOT EDIT - Generated by OrchestratorAgent
"""

import asyncio
import logging
from pathlib import Path
from typing import Dict, Any, Optional

from src.agents.market_data_agent.run import MarketDataAgent
from src.agents.polymarket_agent.run import PolymarketAgent
from src.agents.reasoning_agent.run import ReasoningAgent

logger = logging.getLogger(__name__)


async def task_1() -> Dict[str, Any]:
    """
    Task 1: Retrieve the predictions for when the federal shutdown is ending during the last 10 days
    Agent: polymarket_agent
    """
    logger.info(f"Starting task 1: Retrieve the predictions for when the federal shut...")
    try:
        agent = PolymarketAgent()
        output_path = agent.run(query="retrieve the predictions for when the federal shutdown is ending during the last 10 days", session_id=None, limit=10)
        
        logger.info(f"Task 1 completed: {output_path}")
        
        # Read output
        import json
        with open(output_path, 'r') as f:
            output_data = json.load(f)
        
        return {
            'status': 'success',
            'task_id': 1,
            'agent': 'polymarket_agent',
            'output_path': str(output_path),
            'data': output_data,
            'error': None
        }
    except Exception as e:
        logger.error(f"Task 1 failed: {e}")
        return {
            'status': 'failed',
            'task_id': 1,
            'agent': 'polymarket_agent',
            'output_path': None,
            'data': None,
            'error': str(e)
        }


async def task_2() -> Dict[str, Any]:
    """
    Task 2: Retrieve the market price data for the last 10 days
    Agent: market_data_agent
    """
    logger.info(f"Starting task 2: Retrieve the market price data for the last 10 day...")
    try:
        agent = MarketDataAgent()
        output_path = agent.run(template="all_valid", params={}, columns=None, limit=None)
        
        logger.info(f"Task 2 completed: {output_path}")
        
        # Read output
        import json
        with open(output_path, 'r') as f:
            output_data = json.load(f)
        
        return {
            'status': 'success',
            'task_id': 2,
            'agent': 'market_data_agent',
            'output_path': str(output_path),
            'data': output_data,
            'error': None
        }
    except Exception as e:
        logger.error(f"Task 2 failed: {e}")
        return {
            'status': 'failed',
            'task_id': 2,
            'agent': 'market_data_agent',
            'output_path': None,
            'data': None,
            'error': str(e)
        }


async def task_3() -> Dict[str, Any]:
    """
    Task 3: Analyze the change in market price data over the last 10 days
    Agent: reasoning_agent
    """
    logger.info(f"Starting task 3: Analyze the change in market price data over the l...")
    try:
        agent = ReasoningAgent()
        output_path = agent.run(query="analyze the change in market price data over the last 10 days", session_id=None)
        
        logger.info(f"Task 3 completed: {output_path}")
        
        # Read output
        import json
        with open(output_path, 'r') as f:
            output_data = json.load(f)
        
        return {
            'status': 'success',
            'task_id': 3,
            'agent': 'reasoning_agent',
            'output_path': str(output_path),
            'data': output_data,
            'error': None
        }
    except Exception as e:
        logger.error(f"Task 3 failed: {e}")
        return {
            'status': 'failed',
            'task_id': 3,
            'agent': 'reasoning_agent',
            'output_path': None,
            'data': None,
            'error': str(e)
        }


async def task_4() -> Dict[str, Any]:
    """
    Task 4: Compare the predictions for the federal shutdown ending with the changes in market price data
    Agent: reasoning_agent
    """
    logger.info(f"Starting task 4: Compare the predictions for the federal shutdown e...")
    try:
        agent = ReasoningAgent()
        output_path = agent.run(query="compare the predictions for the federal shutdown ending with the changes in market price data", session_id=None)
        
        logger.info(f"Task 4 completed: {output_path}")
        
        # Read output
        import json
        with open(output_path, 'r') as f:
            output_data = json.load(f)
        
        return {
            'status': 'success',
            'task_id': 4,
            'agent': 'reasoning_agent',
            'output_path': str(output_path),
            'data': output_data,
            'error': None
        }
    except Exception as e:
        logger.error(f"Task 4 failed: {e}")
        return {
            'status': 'failed',
            'task_id': 4,
            'agent': 'reasoning_agent',
            'output_path': None,
            'data': None,
            'error': str(e)
        }



async def main() -> list:
    """Main orchestration function - sequential/mixed execution."""
    logger.info("Starting task execution")
    all_results = []

    # Execute parallel group 1
    group_results = await asyncio.gather(task_1(), task_2())
    all_results.extend(group_results)

    # Execute task 3
    result_3 = await task_3()
    all_results.append(result_3)

    # Execute task 4
    result_4 = await task_4()
    all_results.append(result_4)

    logger.info("All tasks completed")
    return all_results



if __name__ == "__main__":
    # Run the orchestration
    results = asyncio.run(main())
    
    # Print summary
    print("\n" + "="*60)
    print("ORCHESTRATION COMPLETE")
    print("="*60)
    for i, result in enumerate(results, 1):
        status = "✓ SUCCESS" if result.get('status') == 'success' else "✗ FAILED"
        print(f"Task {i}: {status}")
        if result.get('error'):
            print(f"  Error: {result['error']}")
    print("="*60)
