"""
Auto-generated orchestration script.
DO NOT EDIT - Generated by OrchestratorAgent
"""

import asyncio
import logging
from pathlib import Path
from typing import Dict, Any, Optional

from src.agents.market_data_agent.run import MarketDataAgent

logger = logging.getLogger(__name__)


async def task_1() -> Dict[str, Any]:
    """
    Task 1: Find the most recent date when ZN price closed between 112.5 and 112.9
    Agent: market_data_agent
    """
    logger.info(f"Starting task 1: Find the most recent date when ZN price closed bet...")
    try:
        agent = MarketDataAgent()
        output_path = agent.run(template="custom", params={'conditions': 'symbol LIKE ? AND price BETWEEN ? AND ? AND is_valid = 1', 'values': ['%ZN%', 112.5, 112.9]}, columns=None, limit=1, order_by_column="file_date", order_by_direction="DESC")
        
        logger.info(f"Task 1 completed: {output_path}")
        
        # Read output
        import json
        with open(output_path, 'r') as f:
            output_data = json.load(f)
        
        return {
            'status': 'success',
            'task_id': 1,
            'agent': 'market_data_agent',
            'output_path': str(output_path),
            'data': output_data,
            'error': None
        }
    except Exception as e:
        logger.error(f"Task 1 failed: {e}")
        return {
            'status': 'failed',
            'task_id': 1,
            'agent': 'market_data_agent',
            'output_path': None,
            'data': None,
            'error': str(e)
        }



async def main() -> list:
    """Main orchestration function - parallel execution."""
    logger.info("Starting parallel execution of 1 tasks")
    
    results = await asyncio.gather(
        task_1()
    )
    
    logger.info("All tasks completed")
    return list(results)



if __name__ == "__main__":
    # Run the orchestration
    results = asyncio.run(main())
    
    # Print summary
    print("\n" + "="*60)
    print("ORCHESTRATION COMPLETE")
    print("="*60)
    for i, result in enumerate(results, 1):
        status = "✓ SUCCESS" if result.get('status') == 'success' else "✗ FAILED"
        print(f"Task {i}: {status}")
        if result.get('error'):
            print(f"  Error: {result['error']}")
    print("="*60)
